"""initial_schema

Revision ID: 10bcd26b623c
Revises: 
Create Date: 2026-09-12 05:51:47.874588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bcd26b623c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('horizon_h', sa.Integer(), nullable=False),
    sa.Column('mae_mw', sa.Float(), nullable=False),
    sa.Column('rmse_mw', sa.Float(), nullable=False),
    sa.Column('pinball_p10', sa.Float(), nullable=False),
    sa.Column('pinball_p50', sa.Float(), nullable=False),
    sa.Column('pinball_p90', sa.Float(), nullable=False),
    sa.Column('crps', sa.Float(), nullable=False),
    sa.Column('picp_80', sa.Float(), nullable=False),
    sa.Column('skill_vs_persistence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('plants_processed', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('avc_mw', sa.Float(), nullable=False),
    sa.Column('pool_id', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pooling_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('individual_penalty_inr', sa.Float(), nullable=False),
    sa.Column('pooled_penalty_inr', sa.Float(), nullable=False),
    sa.Column('savings_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulation_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_name', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('clause', sa.String(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('valid_time', sa.DateTime(), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_mw', sa.Float(), nullable=False),
    sa.Column('soc_mwh', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dsm_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('valid_time', sa.DateTime(), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('schedule_mw', sa.Float(), nullable=False),
    sa.Column('expected_penalty_inr', sa.Float(), nullable=False),
    sa.Column('p50_penalty_inr', sa.Float(), nullable=False),
    sa.Column('optimised_penalty_inr', sa.Float(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('x_value', sa.Float(), nullable=False),
    sa.Column('savings_inr', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('valid_time', sa.DateTime(), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('p05', sa.Float(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('p95', sa.Float(), nullable=False),
    sa.Column('calibrated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_plant_valid', 'forecasts', ['plant_id', 'valid_time'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('schedule_mw', sa.Float(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_plant_date', 'schedules', ['plant_id', 'schedule_date'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('issue_time', sa.DateTime(), nullable=False),
    sa.Column('valid_time', sa.DateTime(), nullable=False),
    sa.Column('ghi_w_m2', sa.Float(), nullable=True),
    sa.Column('dni_w_m2', sa.Float(), nullable=True),
    sa.Column('dhi_w_m2', sa.Float(), nullable=True),
    sa.Column('wind_10m', sa.Float(), nullable=True),
    sa.Column('wind_80m', sa.Float(), nullable=True),
    sa.Column('wind_120m', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_forecast_plant_valid', 'weather_forecasts', ['plant_id', 'valid_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_forecast_plant_valid', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index('ix_schedule_plant_date', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_forecast_plant_valid', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('dsm_results')
    op.drop_table('actions')
    op.drop_table('regulation_chunks')
    op.drop_table('pooling_results')
    op.drop_table('plants')
    op.drop_table('job_runs')
    op.drop_table('backtest_metrics')
    # ### end Alembic commands ###
